// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navarro_Repo_Pattern.Infra;

#nullable disable

namespace Navarro_Repo_Pattern.Infra.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20250406201831_add_curso")]
    partial class add_curso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ExigeInscricao")
                        .HasColumnType("bit");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Postagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("PostagemId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Postagem", b =>
                {
                    b.HasOne("Navarro_Repo_pattern.Domain.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Navarro_Repo_pattern.Domain.Postagem", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Usuario", b =>
                {
                    b.HasOne("Navarro_Repo_pattern.Domain.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Navarro_Repo_pattern.Domain.Evento", null)
                        .WithMany("Inscritos")
                        .HasForeignKey("EventoId");

                    b.HasOne("Navarro_Repo_pattern.Domain.Postagem", null)
                        .WithMany("Curtidas")
                        .HasForeignKey("PostagemId");

                    b.HasOne("Navarro_Repo_pattern.Domain.Usuario", null)
                        .WithMany("Seguidores")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Evento", b =>
                {
                    b.Navigation("Inscritos");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Postagem", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");
                });

            modelBuilder.Entity("Navarro_Repo_pattern.Domain.Usuario", b =>
                {
                    b.Navigation("Seguidores");
                });
#pragma warning restore 612, 618
        }
    }
}
